# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180420_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 17, 18, 35, 718723, tzinfo=utc)),
        ),
    ]
